# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app


#RUN apt-get update && \
#apt-get install -y --no-install-recommends \
#build-essential \
#libpq-dev \
#libmagic1 \
#&& rm -rf /var/lib/apt/lists/*


# Copy the requirements file into the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . /app

# Expose the port the app runs on
EXPOSE 8181

# Command to run the application
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8181"]